### ISSUE TITLE
Deploy the website 

### ISSUE THREAD

**Issue by sagar-io** [udyat-miet/udyat-website#1]
Deploy the website on any of the the free service provider like Netlify or Vercel and add the deploy link into the README.md file

**Comment by pradeepk07** [comment]
udyatmiet.netlify.app site deployed at netlify

**Comment by sagar-io** [comment]
Nice, now update the link in the readme file

**Comment by sagar-io** [comment]
and open a pull request

**Comment by sagar-io** [comment]
@pradeepk07 Please open a pull request, 8 marks will be assigned only after that.

**Comment by sagar-io** [comment]
@pradeepk07 let me know if you need any help.

**Comment by pradeepk07** [comment]
done
