### ISSUE TITLE
Implement a basic form for joining the team

### ISSUE THREAD

**Issue by sagar-io** [udyat-miet/udyat-website#2]
Make a basic form in a new HTML file. 
The form will take the values like Name, college email id, contact number and a submit button.
Connect that HTML file with the below button and rename the below button by "Submit Details".
![image](https://github.com/udyat-miet/udyat-website/assets/86215447/43c6e555-b092-456a-b61a-ac21987f5785)

**Note** - No need to implement submit button functionality.

**Comment by VikasKumar8566** [comment]
I want to work.

**Comment by sagar-io** [comment]
Okay go ahead

**Comment by AnuprashGautam** [comment]
We replaced the "SUBMIT CV" button by " SUBMIT DETAILS" and linked the html form page. Here are screenshots
<img width="960" alt="Screenshot 2023-12-09 213254" src="https://github.com/udyat-miet/udyat-website/assets/137447058/3cca3a2e-d4c3-47a8-b5ab-90abac37b41a">
<img width="960" alt="Screenshot 2023-12-09 213315" src="https://github.com/udyat-miet/udyat-website/assets/137447058/256b92b0-242e-4a0c-8d4a-e499faa9531a">
<img width="960" alt="Screenshot 2023-12-09 213345" src="https://github.com/udyat-miet/udyat-website/assets/137447058/dd44cebc-9db5-4132-a919-8780786e2490">

**Comment by Mittal-Chirag** [comment]
I have replaced the "SUBMIT CV" button with "SUBMIT DETALS" . while clicking the button it directing you to google form but now it direct you to simply login page. here are some screenshots of that:
![Screenshot 2023-12-09 213408](https://github.com/udyat-miet/udyat-website/assets/153297675/2f18cbcf-55e6-40a9-8edf-405bb7711534)
![Screenshot 2023-12-09 213358](https://github.com/udyat-miet/udyat-website/assets/153297675/709362e9-04e6-4c03-ab4e-550056be7cf2)
![Screenshot 2023-12-09 213352](https://github.com/udyat-miet/udyat-website/assets/153297675/a79d7945-5ee2-492b-80bf-565d411f4a5e)
![Screenshot 2023-12-09 213328](https://github.com/udyat-miet/udyat-website/assets/153297675/7f6013d6-c0f3-4333-9201-75855367a7a9)

**Comment by sagar-io** [comment]
All guys open a pull request, I'll evaluate and merge accordingly.

**Comment by VikasKumar8566** [comment]
body me padding left kar sakte hain .
kyoki ye complete page pe aa raha hain
