### ISSUE TITLE
Wrong style used

### ISSUE THREAD

**Issue by ShaShaurya** [udyat-miet/udyat-website#3]
Here is the previously used issue
![Screenshot 2023-12-09 212907](https://github.com/udyat-miet/udyat-website/assets/113677008/831ed39b-1dd3-442c-ad98-f40c225881d0)

And this is the corrected one
![image](https://github.com/udyat-miet/udyat-website/assets/113677008/b49c63cf-adf9-4499-a680-75f73180396e)

**Comment by sagar-io** [comment]
Good ! 
Go ahead an open a pull request.
