### ISSUE TITLE
Changed "text-size" to "font-size"

### ISSUE THREAD

**Issue by AnuprashGautam** [udyat-miet/udyat-website#4]
<img width="689" alt="Screenshot 2023-12-09 214130" src="https://github.com/udyat-miet/udyat-website/assets/137447058/23fab251-5566-4e69-a1d2-e65a748f067d">
<img width="680" alt="Screenshot 2023-12-09 214200" src="https://github.com/udyat-miet/udyat-website/assets/137447058/6e4f7190-fabb-441e-b45f-1d1d5e1c189b">

**Comment by sagar-io** [comment]
Sorry, This issue is already assigned.
see - https://github.com/udyat-miet/udyat-website/issues/3

**Comment by sagar-io** [comment]
Find a new issue, there're multiple
