### ISSUE TITLE
Changed style  

### ISSUE THREAD

**Issue by Mittal-Chirag** [udyat-miet/udyat-website#5]
You have used a wrong style. Instead of using "Font-size" you have used "text-size". I have done it.
![Screenshot 2023-12-09 214157](https://github.com/udyat-miet/udyat-website/assets/153297675/94334a50-fc79-4a3f-8c8d-f7638064d7f0)
![Screenshot 2023-12-09 214134](https://github.com/udyat-miet/udyat-website/assets/153297675/7b1f4187-6877-4828-9f71-e3dc42a1bb52)

**Comment by sagar-io** [comment]
Sorry, This issue is already assigned to another person. https://github.com/udyat-miet/udyat-website/issues/2

**Comment by sagar-io** [comment]
Please find other issues, there're many. even in Readme
