### ISSUE TITLE
Error in font-awsome,css

### ISSUE THREAD

**Issue by ShaShaurya** [udyat-miet/udyat-website#8]
The error is occurring in one filter used i.e. -ms-filter in rotating text

**Comment by sagar-io** [comment]
Please elaborate or share any screenshot

**Comment by ShaShaurya** [comment]
![Screenshot 2023-12-09 223207](https://github.com/udyat-miet/udyat-website/assets/113677008/5123570b-a1cc-4a7f-90d0-849b51eb4dd9)

**Comment by sagar-io** [comment]
Hey, that's a part of font-awesome library. Don't update that.
