### ISSUE TITLE
Error in code in style.css

### ISSUE THREAD

**Issue by ShaShaurya** [udyat-miet/udyat-website#9]
This is first error
![image](https://github.com/udyat-miet/udyat-website/assets/113677008/fd4a10e0-b99e-4e42-9932-ab0ac7779277)
 This is second error
![image](https://github.com/udyat-miet/udyat-website/assets/113677008/81877241-906b-43f9-883e-06c2a899170b)

Now after correcting the errors
![image](https://github.com/udyat-miet/udyat-website/assets/113677008/6a30c511-1c94-4a9e-aadb-2da0854a23e3)
![image](https://github.com/udyat-miet/udyat-website/assets/113677008/7abc22ce-ded1-4bf3-afb3-a621bb12cb5f)

**Comment by sagar-io** [comment]
Go ahead and make pull request for it.
